from .Embedding import Embeddings
from .synonym import Synonym
from .spellcheck import Corrector
from .summerization import Summerize
from .unicode_nepali import Unicode
from .preeti_unicode import preeti
from .ocr import OCR
from .Nepali_tokenizer import Tokenizer
from .sentence_similar import Avg_vector_similar
from .news_scrap import extract_news
from .news_latest import UpdateNews