from nepali_nlp.embedding import Embeddings
from nepali_nlp.synonym import Synonym
from nepali_nlp.spellcheck import Corrector
from nepali_nlp.summarization import Summarize
from nepali_nlp.unicode_nepali import Unicode
from nepali_nlp.preeti_unicode import preeti
from nepali_nlp.ocr import OCR
from nepali_nlp.nepali_tokenizer import Tokenizer
from nepali_nlp.sentence_similar import Avg_vector_similar
from nepali_nlp.news_scrap import extract_news
from nepali_nlp.news_latest import UpdateNews
from nepali_nlp.stemmer import Stem
