from PIL import Image
import pytesseract
import cv2
import os


def tesseract_ocr(image,lang='nep'):
    """This function helps to generate text from image
    
    Arguments:
        image {string} -- [Location of image.]
    
    Keyword Arguments:
        lang {str} -- [language for OCR] (default: {'nep'})
    
    Returns:
        [string] -- [Text generated by OCR.]
    """
    assert lang in ['eng','nep'], 'specified language is not available at the moment'

    image_ = cv2.imread(image)
    gray_ = cv2.cvtColor(image_, cv2.COLOR_BRG2GRAY)
    
    if lang=='nep':
        tessdata_dir_config = r'--tessdata-dir "../tesserdata"'
        text = pytesseract.image_to_string(gray_, lang=lang, config=tessdata_dir_config)
        
        return text
    
    text = pytesseract.image_to_string(gray_)#if 'eng' is the choice
    return text